save

diff --git a/.github/workflows/sync-fork.yml b/.github/workflows/sync-fork.yml
--- a/.github/workflows/sync-fork.yml
+++ b/.github/workflows/sync-fork.yml
@@ -1,34 +1,40 @@
-name: Sync Fork
+name: Upstream Sync
+
+permissions:
+  contents: write
 
 on:
   schedule:
-    # 每天凌晨2点执行同步操作
-    - cron: '0 2 * * *'
+    - cron: "0 0 * * *" # every day
   workflow_dispatch:
 
 jobs:
-  sync:
+  sync_latest_from_upstream:
+    name: Sync latest commits from upstream repo
     runs-on: ubuntu-latest
+    if: ${{ github.event.repository.fork }}
+
     steps:
-      - name: Checkout
+      # Step 1: run a standard checkout action
+      - name: Checkout target repo
         uses: actions/checkout@v3
+
+      # Step 2: run the sync action
+      - name: Sync upstream changes
+        id: sync
+        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
         with:
-          fetch-depth: 0
+          upstream_sync_repo: ACL4SSR/ACL4SSR
+          upstream_sync_branch: master
+          target_sync_branch: master
+          target_repo_token: ${{ secrets.GITHUB_TOKEN }} # automatically generated, no need to set
 
-      - name: Set up Git
+          # Set test_mode true to run tests instead of the true action!!
+          test_mode: false
+
+      - name: Sync check
+        if: failure()
         run: |
-          git config user.name "${{ github.actor }}"
-          git config user.email "${{ github.actor }}@users.noreply.github.com"
-
-      - name: Add upstream remote
-        run: git remote add upstream https://github.com/ACL4SSR/ACL4SSR
-
-      - name: Fetch upstream
-        run: git fetch upstream
-
-      - name: Sync all branches
-        run: |
-          git branch -r | grep 'upstream/' | grep -v 'HEAD' | grep -v '->' | sed 's/^[[:space:]]*upstream\///' | while read branch; do
-            git checkout -B $branch upstream/$branch
-            git push -f origin $branch
-          done    
+          echo "[Error] 由于上游仓库的 workflow 文件变更，导致 GitHub 自动暂停了本次自动更新，你需要手动 Sync Fork 一次，详细教程请查看：https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/README_CN.md#%E6%89%93%E5%BC%80%E8%87%AA%E5%8A%A8%E6%9B%B4%E6%96%B0"
+          echo "[Error] Due to a change in the workflow file of the upstream repository, GitHub has automatically suspended the scheduled automatic update. You need to manually sync your fork. Please refer to the detailed tutorial for instructions: https://github.com/Yidadaa/ChatGPT-Next-Web#enable-automatic-updates"
+          exit 1
